### ISSUE TITLE
settings.jsonにregexフィルタを追加してください

### ISSUE THREAD

**Issue by rasbayri** [led-mirage/AivoClip#1]
なので、余計な発音はしない。

**Comment by led-mirage** [comment]
v0.3.0で置換する文字列を設定できるようにしました。
お試しください。

例えば、括弧内の文字列とURLを除去したい場合は、settings.jsonファイル内で以下のように設定します。
```json
    "replacements": [
        {
            "pattern": "\\(.*?\\)|（.*?）",
            "replacement": ""
        },
        {
            "pattern": "https?:\\/\\/(?:[\\w\\-\\.]+)+(?:[\\w\\.\\/\\?%&=]*)?",
            "replacement": ""
        }
    ]
```

**Comment by rasbayri** [comment]
うわーありがとうございます！感謝してる！もしかして、できれば、テキストをクリップボードにコピーするまでの待ち時間の設定
１ｍｓとか２ｍｓとか３ｍｓとか
ちょっと説明は難しいけど良ければこのTextractor見てください
結成でゲームを読んでいます
https://gofile.io/d/QXdhod

**Comment by led-mirage** [comment]
セキュリティの観点からリンク先のオブジェクトを確認することはできないのですが、
Textractorがゲームのテキストを抽出するツールであることは理解しました。

ご要望の内容を確認したいのですが、
AivoClipがクリップボードにテキストがコピーされたのを検知してから、
読み上げるまでの待ち時間を設定できるようにしてほしい、ということで合っていますか？

ただ、AivoClipはクリップボードを一定間隔（500ms）で監視しているため、
1ms、2msといった短い間隔で待ち時間を設定できたとしても、あまり効果がありません。

どのような使い方を想定しているのか、簡単でいいのでお教えいただけますか？

<hr>

I understand your request, but due to security reasons, I cannot verify the object linked. I comprehend that Textractor is a tool for extracting text from games.

To confirm, are you asking for a feature in AivoClip that allows setting a delay time before the text copied to the clipboard is read aloud? If so, I should note that AivoClip monitors the clipboard at a fixed interval of 500ms. Therefore, setting a delay as short as 1ms or 2ms wouldn’t have much effect.

Could you please share a bit about how you intend to use this feature? This will help us better understand your needs.

**Comment by led-mirage** [comment]
一旦クローズさせていただきます。
